<a href="https://colab.research.google.com/github/JakubPac/kurs_data_science/blob/main/Algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Norma wektora, długość wektora w R^2

In [4]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [5]:
np.linalg.norm(v1)

np.float64(4.123105625617661)

Norma euklidesowa R^n


In [6]:
v2 = np.array([-10, 10, 13])
v2

array([-10,  10,  13])

In [7]:
np.linalg.norm(v2)

np.float64(19.209372712298546)

Odległóść dwóch punktów na płaszczyźnie

In [8]:
x1 = np.array([3, 0])
x2 = np.array([0, 4])

In [9]:
np.linalg.norm(x1 - x2)

np.float64(5.0)

Odległóść dwóch punktów w przestrzeni R^n

In [10]:
x1 = np.array([3, 0, 1])
x2 = np.array([0, 4, 2])

In [11]:
np.linalg.norm(x1 - x2)

np.float64(5.0990195135927845)

Mnożenie macierzy

In [12]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])

In [13]:
print(X)
print(Y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [14]:
Z = X.dot(Y)

In [15]:
print(Z)

[[ 2]
 [-6]]


In [16]:
X = np.array([[2, -1, 3], [3, 1, 0]])
Y = np.array([[2, 1, -1], [0,-1, 2], [3, 2, 0]])

In [17]:
Z = X.dot(Y)
print(Z)

[[13  9 -4]
 [ 6  2 -1]]


Wyznacznik macierzy


In [18]:
A = np.array([[2, 4], [-1, 3]])
A

array([[ 2,  4],
       [-1,  3]])

In [21]:
round(np.linalg.det(A))

10

Ślad macierzy


In [22]:
A = np.array([[2, 4], [-1, 3]])

In [23]:
np.linalg.trace(A)

np.int64(5)


Macierz jednostkowa


In [25]:
B = np.eye(5, dtype = 'int')
B

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Macierz odwrotna

In [26]:
A = np.array([[2, 4], [-1, 3]])
A

array([[ 2,  4],
       [-1,  3]])

In [30]:
B = np.linalg.inv(A)

In [31]:
A.dot(B)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [32]:
B.dot(A)

array([[ 1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

Macierz transponowana


In [33]:
A = np.array([[2, 4], [-1, 3]])
A

array([[ 2,  4],
       [-1,  3]])

In [34]:
A.T

array([[ 2, -1],
       [ 4,  3]])

In [35]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

Rozwiązywanie układów równań

In [38]:
A = np.array([[2, 4], [1, -1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [40]:
B = np.array([[10] , [-1]])
B

array([[10],
       [-1]])

In [41]:
A_inv = np.linalg.inv(A)

In [42]:
X = A_inv.dot(B)
X

array([[1.],
       [2.]])

In [43]:
X.shape

(2, 1)