<a href="https://colab.research.google.com/github/JakubPac/kurs_data_science/blob/main/keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import plotly.express as px

In [4]:
from tensorflow.keras.models import Sequential

In [6]:
model = Sequential()
print(model)

<Sequential name=sequential_1, built=False>


In [7]:
from tensorflow.keras.layers import Dense

In [9]:
model.add(Dense(units = 4, input_shape = (10,)))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [10]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 4)              │            44 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 44 (176.00 B)

 Trainable params: 44 (176.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.add(Dense(units = 2))

In [12]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 4)              │            44 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 2)              │            10 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 54 (216.00 B)

 Trainable params: 54 (216.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
from tensorflow.keras.activations import linear
randomdata = np.linspace(-3, 3, 300)
data = pd.DataFrame({'data': randomdata, 'linear' : linear(randomdata)})
data.head()

,data,linear
0,-3.000000,-3.000000
1,-2.979933,-2.979933
2,-2.959866,-2.959866
3,-2.939799,-2.939799
4,-2.919732,-2.919732


In [14]:
px.line(data, x = 'data', y = 'linear', width = 500, height = 400, range_y=[-3,3])

In [15]:
from tensorflow.keras.activations import sigmoid
randomdata = np.linspace(-3, 3, 300)
data = pd.DataFrame({'data': randomdata, 'sigmoid' : sigmoid(randomdata)})
data.head()

,data,sigmoid
0,-3.000000,0.047426
1,-2.979933,0.048341
2,-2.959866,0.049272
3,-2.939799,0.050221
4,-2.919732,0.051187


In [19]:
px.line(data, x = 'data', y = 'sigmoid', width = 500, height = 400, range_y=[-0.5,1.5])

In [20]:
from tensorflow.keras.activations import relu
randomdata = np.linspace(-3, 3, 300)
data = pd.DataFrame({'data': randomdata, 'relu' : relu(randomdata)})
data.head()

,data,relu
0,-3.000000,0.0
1,-2.979933,0.0
2,-2.959866,0.0
3,-2.939799,0.0
4,-2.919732,0.0


In [22]:
px.line(data, x = 'data', y = 'relu', width = 500, height = 400, range_y=[-0.5,3])

In [23]:
from tensorflow.keras.activations import tanh
randomdata = np.linspace(-3, 3, 300)
data = pd.DataFrame({'data': randomdata, 'tanh' : tanh(randomdata)})
data.head()

,data,tanh
0,-3.000000,-0.995055
1,-2.979933,-0.994853
2,-2.959866,-0.994643
3,-2.939799,-0.994424
4,-2.919732,-0.994196


In [24]:
px.line(data, x = 'data', y = 'tanh', width = 500, height = 400, range_y=[-1,1])

In [25]:
model = Sequential()
model.add(Dense(units = 8, activation = 'relu', input_shape = (10,)))
model.add(Dense(units = 1, activation = 'sigmoid'))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# klasyfikacja binarna
model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

# klsyfikacja wieloklasowa
model.compile(optimizer = 'rmsprop',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])

#regresja
model.compile(optimizer = 'rmsprop',
              loss = 'mse')

klasyfikacja binarna

In [26]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size = (10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [27]:
data[:3]

array([[-1.24620291e+00,  1.72779935e+00,  4.96129784e-01,
        -1.95591419e+00,  4.32608466e-01,  3.69519934e-02,
         5.37279026e-01, -2.40334171e-01,  1.45011025e+00,
        -1.10422133e-01, -3.81068467e-01, -1.73644303e+00,
        -1.35700892e+00, -1.21784741e+00, -6.33806336e-01,
        -5.62572672e-01, -5.37926442e-01,  7.97521733e-01,
        -2.97921786e-01,  1.14635308e+00,  2.82387783e-01,
        -2.16688270e-01, -8.68600615e-01, -1.35553978e-01,
         3.05423515e+00,  6.47917858e-01,  1.05939057e+00,
        -3.51054655e-01,  1.20171506e+00,  5.74785375e-01,
         6.33222548e-01, -4.39585803e-01, -1.73561043e+00,
        -7.85594306e-01, -1.51346479e+00,  5.90346452e-01,
         1.12098436e+00,  4.12082377e-01, -5.19049487e-01,
         7.92014810e-01, -4.14520721e-01, -2.81048916e-01,
         3.44105063e-02,  1.36662700e+00, -5.98366139e-01,
         1.01072115e+00, -1.13531790e+00,  2.68722319e-01,
        -1.02621558e-01, -1.83441171e-01,  6.83276275e-0

In [28]:
labels[:10]

array([[0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [29]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(units = 1, activation = 'sigmoid'))

model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

model.fit(data, labels, epochs = 20)

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.4941 - loss: 0.7819
Epoch 2/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5520 - loss: 0.6917
Epoch 3/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5803 - loss: 0.6739
Epoch 4/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6145 - loss: 0.6567
Epoch 5/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6318 - loss: 0.6438
Epoch 6/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6524 - loss: 0.6300
Epoch 7/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6667 - loss: 0.6177
Epoch 8/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6906 - loss: 0.5989
Epoch 9/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7047 - loss: 0.5840
Epoch 10/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7124 - loss: 0.5733
Epoch 11/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7328 - loss: 0.5569
Epoch 12/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy

In [30]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(units = 1, activation = 'sigmoid'))

model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

model.fit(data, labels, epochs = 20, batch_size = 30)

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4939 - loss: 0.7593
Epoch 2/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5497 - loss: 0.6910
Epoch 3/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5801 - loss: 0.6738
Epoch 4/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6213 - loss: 0.6559
Epoch 5/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6247 - loss: 0.6479
Epoch 6/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6544 - loss: 0.6293
Epoch 7/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6736 - loss: 0.6188
Epoch 8/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6960 - loss: 0.5969
Epoch 9/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7054 - loss: 0.5806
Epoch 10/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7180 - loss: 0.5713
Epoch 11/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7365 - loss: 0.5491
Epoch 12/20
334/334 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy

In [31]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(units = 1, activation = 'sigmoid'))

model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

model.fit(data, labels, epochs = 20, batch_size = 32, validation_split=0.2)

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5119 - loss: 0.7758 - val_accuracy: 0.5265 - val_loss: 0.7114
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5517 - loss: 0.6945 - val_accuracy: 0.5130 - val_loss: 0.7096
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5849 - loss: 0.6740 - val_accuracy: 0.5170 - val_loss: 0.7114
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6114 - loss: 0.6552 - val_accuracy: 0.5195 - val_loss: 0.7129
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6300 - loss: 0.6437 - val_accuracy: 0.5070 - val_loss: 0.7190
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6539 - loss: 0.6275 - val_accuracy: 0.5065 - val_loss: 0.7260
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6793 - loss: 0.6080 - val_accuracy: 0.5100 - val_loss: 0.7307
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6893 - loss: 0.5971 - val_accuracy: 0.5075 - val_

In [33]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(units = 1, activation = 'sigmoid'))

model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

history = model.fit(data, labels, epochs = 20, batch_size = 32, validation_split=0.2, verbose = 0)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



In [34]:
metrics = history.history
metrics.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [35]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(units = 1, activation = 'sigmoid'))

model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

history = model.fit(data, labels, epochs = 20, batch_size = 32, validation_split=0.2, verbose = 1)

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5046 - loss: 0.7807 - val_accuracy: 0.5250 - val_loss: 0.7097
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5453 - loss: 0.6920 - val_accuracy: 0.5305 - val_loss: 0.7043
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5998 - loss: 0.6653 - val_accuracy: 0.5240 - val_loss: 0.7080
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6154 - loss: 0.6519 - val_accuracy: 0.5230 - val_loss: 0.7080
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6445 - loss: 0.6374 - val_accuracy: 0.5260 - val_loss: 0.7132
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6639 - loss: 0.6241 - val_accuracy: 0.5275 - val_loss: 0.7146
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6895 - loss: 0.6039 - val_accuracy: 0.5245 - val_loss: 0.7206
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7012 - loss: 0.5945 - val_accuracy: 0.5225 - val_

In [36]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2,size = (5,1))

In [38]:
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step


array([[0.26470143],
       [0.24423255],
       [0.36654177],
       [0.13411283],
       [0.30931622]], dtype=float32)

In [39]:
np.argmax(model.predict(test_data), axis = 1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([0, 0, 0, 0, 0])

klasyfikacja wieloklasowa

In [41]:
data = np.random.randn(10000, 150)
labels = np.random.randint(10, size = (10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [42]:
labels[:10]

array([[4],
       [1],
       [1],
       [4],
       [5],
       [1],
       [7],
       [7],
       [5],
       [4]])

In [44]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [45]:
labels[1]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(units = 10, activation = 'softmax'))

model.compile(optimizer = 'rmsprop',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])

model.fit(data, labels, epochs = 30, batch_size = 32, validation_split=0.2)

Epoch 1/30


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0897 - loss: 2.6259 - val_accuracy: 0.0985 - val_loss: 2.4511
Epoch 2/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1177 - loss: 2.3623 - val_accuracy: 0.1010 - val_loss: 2.4000
Epoch 3/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.1396 - loss: 2.2780 - val_accuracy: 0.1055 - val_loss: 2.3876
Epoch 4/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.1784 - loss: 2.2285 - val_accuracy: 0.0970 - val_loss: 2.3870
Epoch 5/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1947 - loss: 2.1955 - val_accuracy: 0.0930 - val_loss: 2.3973
Epoch 6/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2174 - loss: 2.1713 - val_accuracy: 0.0940 - val_loss: 2.4078
Epoch 7/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2318 - loss: 2.1488 - val_accuracy: 0.0920 - val_loss: 2.4166
Epoch 8/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2385 - loss: 2.1296 - val_accuracy: 0.0920 - val_

In [47]:
test_data = np.random.random((10,150))
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step


array([[0.06166071, 0.06882022, 0.01399922, 0.19210012, 0.15145351,
        0.11566465, 0.09562697, 0.12694946, 0.08786162, 0.08586358],
       [0.06281079, 0.11401916, 0.04773058, 0.07924359, 0.12011567,
        0.18986985, 0.11853279, 0.07462616, 0.10182176, 0.09122965],
       [0.10255731, 0.09861618, 0.02466171, 0.08192348, 0.14088075,
        0.17868355, 0.11103883, 0.08238949, 0.07303834, 0.10621033],
       [0.04197709, 0.09051337, 0.01994624, 0.15632199, 0.24348484,
        0.15674853, 0.08018827, 0.05531607, 0.0754423 , 0.08006127],
       [0.03566093, 0.03632363, 0.01783173, 0.12469154, 0.197579  ,
        0.15456222, 0.06859366, 0.08009425, 0.20042406, 0.08423904],
       [0.05196027, 0.13196288, 0.04652081, 0.16467424, 0.21312018,
        0.05766203, 0.04789284, 0.09325808, 0.11099226, 0.0819565 ],
       [0.07997294, 0.10124237, 0.02988112, 0.13500276, 0.16430554,
        0.11524425, 0.13192931, 0.11595891, 0.07545957, 0.05100314],
       [0.03726402, 0.07814331, 0.0132135

In [48]:
np.argmax(model.predict(test_data), axis = 1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


array([3, 5, 5, 4, 8, 4, 4, 5, 4, 4])

regresja

In [49]:
data =- np.random.random((10000,150))
labels = 50 * np.random.random(10000)

In [51]:
labels[:10]

array([29.80322026, 21.0147986 , 43.26422963, 45.51572945,  4.13604719,
       23.37906621, 19.5898036 , 48.12161824,  4.63944158, 26.04825137])

In [52]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(units = 1))

model.compile(optimizer = 'rmsprop',
              loss = 'mse')

model.fit(data, labels, epochs = 30, batch_size = 32, validation_split = 0.2)

Epoch 1/30


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 447.3857 - val_loss: 205.2684
Epoch 2/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 208.8040 - val_loss: 205.0000
Epoch 3/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 212.5366 - val_loss: 207.3446
Epoch 4/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 211.5423 - val_loss: 205.2678
Epoch 5/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 206.9678 - val_loss: 205.3187
Epoch 6/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 215.4391 - val_loss: 205.5903
Epoch 7/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 207.3190 - val_loss: 206.3992
Epoch 8/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 210.6007 - val_loss: 207.6519
Epoch 9/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 211.0095 - val_loss: 205.9747
Epoch 10/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 211.3549 - val_loss: 206.0307
Epoch 11/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 212.8340 - val_loss: 206.8266
Epoch 12/30
250/250

In [53]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(units = 1))

model.compile(optimizer = 'rmsprop',
              loss = 'mae',
              metrics = ['mse'])

model.fit(data, labels, epochs = 30, batch_size = 32, validation_split = 0.2)

Epoch 1/30


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 16.1311 - mse: 388.8939 - val_loss: 12.3898 - val_mse: 206.6732
Epoch 2/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.5349 - mse: 210.8210 - val_loss: 12.3841 - val_mse: 206.4399
Epoch 3/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4085 - mse: 207.7650 - val_loss: 12.3938 - val_mse: 208.5212
Epoch 4/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.6407 - mse: 212.5505 - val_loss: 12.3591 - val_mse: 205.8211
Epoch 5/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4801 - mse: 209.0178 - val_loss: 12.5357 - val_mse: 213.6002
Epoch 6/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.5588 - mse: 211.3399 - val_loss: 12.3988 - val_mse: 207.5105
Epoch 7/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4777 - mse: 208.7207 - val_loss: 12.3632 - val_mse: 206.7739
Epoch 8/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.5120 - mse: 210.3846 - val_loss: 12.4388 - val_mse: 209.3456
Epoch 9/30
250/250 