<a href="https://colab.research.google.com/github/JakubPac/kurs_data_science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [120]:
import numpy as np

In [121]:
np.__version__

'2.0.2'

In [122]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__annotations__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsor

In [123]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``o

In [124]:
x = np.array([1, 2 , 3])
x

array([1, 2, 3])

In [125]:
print(x)

[1 2 3]


In [126]:
type(x)

numpy.ndarray

In [127]:
x.ndim

1

In [128]:
x.shape

(3,)

In [129]:
x.size

3

In [130]:
x.dtype

dtype('int64')

In [131]:
y = np.array([1.3, 2.3, 1.4])

In [132]:
print(y)

[1.3 2.3 1.4]


In [133]:
y.dtype

dtype('float64')

In [134]:
x = np.array([[1, 2], [-3, 1]])

In [135]:
x.ndim

2

In [136]:
x.shape

(2, 2)

In [137]:
x.dtype

dtype('int64')

In [138]:
x = np.array([[1, 2, 3], [4, 2, 1]])

In [139]:
print(x)

[[1 2 3]
 [4 2 1]]


In [140]:
x.shape

(2, 3)

In [141]:
x = np.array(
    [[[3, 3, 1],
      [3, 1, 2]],

    [[4, 1 ,3],
     [3, 3, 2]]]
)

In [142]:
print(x)

[[[3 3 1]
  [3 1 2]]

 [[4 1 3]
  [3 3 2]]]


In [143]:
x.shape

(2, 2, 3)

In [144]:
x.ndim

3

In [145]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [146]:
A = np.array([1.2, 2.4, 3.1])
A.dtype

dtype('float64')

In [147]:
A = np.array([1, 2, 3], dtype = 'float')
A.dtype

dtype('float64')

In [148]:
A

array([1., 2., 3.])

In [149]:
A = np.array([1.2, 2.4, 3.1], dtype = 'complex')
A.dtype

dtype('complex128')

In [150]:
A

array([1.2+0.j, 2.4+0.j, 3.1+0.j])

In [151]:
A = np.array([1.2, 2.4, 3.1], dtype = 'int')
A.dtype

dtype('int64')

In [152]:
A

array([1, 2, 3])

In [153]:
A = np.array([True, False])

In [154]:
A.dtype

dtype('bool')

In [155]:
A = np.array([24, 120, 124], dtype = np.int8)

In [156]:
A.dtype

dtype('int8')

In [157]:
A = np.array([24, 120, 230], dtype = np.uint8)
A.dtype

dtype('uint8')

Tworzenie tablic

In [158]:
np.zeros(shape = (4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [159]:
np.zeros(shape = (4, 10), dtype = 'int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [160]:
np.ones(shape = (5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [161]:
np.full(shape = (3, 3), fill_value = 4, dtype = 'int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [162]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
np.arange(start = 5, stop = 10)

array([5, 6, 7, 8, 9])

In [164]:
np.arange(start = 10, stop = 100, step = 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [165]:
np.arange(start = 100, stop = 10, step = -5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15])

In [166]:
np.arange(start = 0, stop = 1, step = 0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [167]:
np.linspace(start = 0, stop = 1, num = 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [168]:
np.linspace(start = 0, stop = 1, num = 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [169]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [170]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [171]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [172]:
A.reshape((-1, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Podstawowe operacje

In [173]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [174]:
A + B

array([6, 0, 7, 4])

In [175]:
A - B

array([0, 2, 1, 0])

In [176]:
A * B

array([ 9, -1, 12,  4])

In [177]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [178]:
np.add(A, B)

array([6, 0, 7, 4])

In [179]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [180]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [181]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [182]:
A + 3

array([6, 4, 7, 5])

In [183]:
A - 3

array([ 0, -2,  1, -1])

In [184]:
2 * A

array([6, 2, 8, 4])

In [185]:
A + 3*B

array([12, -2, 13,  8])

In [186]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])

In [187]:
X * Y

array([[6, 0],
       [2, 0]])

In [188]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [189]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [190]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [191]:
X @ Y

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [192]:
np.random.seed(0)

In [193]:
np.random.randn()

1.764052345967664

In [194]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [195]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [196]:
np.random.rand()

0.1965823616800535

In [197]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [198]:
np.random.rand(10, 4)

array([[0.03918779, 0.28280696, 0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318, 0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145, 0.26538949, 0.52324805],
       [0.09394051, 0.5759465 , 0.9292962 , 0.31856895],
       [0.66741038, 0.13179786, 0.7163272 , 0.28940609],
       [0.18319136, 0.58651293, 0.02010755, 0.82894003],
       [0.00469548, 0.67781654, 0.27000797, 0.73519402],
       [0.96218855, 0.24875314, 0.57615733, 0.59204193],
       [0.57225191, 0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695, 0.81379782]])

In [199]:
np.random.randint(10)

8

In [200]:
np.random.randint(low = 10, high = 101)

26

In [201]:
np.random.randint(low = 10, high = 101, size = 10)

array([34, 39, 31, 35, 90, 70, 71, 93, 43, 42])

In [202]:
np.random.choice([4, 3, 2, 1])

np.int64(4)

In [203]:
np.random.choice(['python', 'java', 'sql'])

np.str_('java')

In [204]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
np.random.shuffle(data)

In [206]:
data

array([2, 4, 1, 3, 9, 0, 8, 7, 5, 6])

Podstawowe funkcje

In [207]:
 np.exp(1)

np.float64(2.718281828459045)

In [210]:
np.sqrt(9)

np.True_

In [212]:
np.all([2, 1, 1])

np.True_

In [213]:
np.any([1, 2, 3])

np.True_

In [214]:
np.any([0, 0, 0])

np.False_

In [218]:
bool(3.2)

True

In [221]:
A = np.random.rand(5)
A

array([0.98404224, 0.26034093, 0.53702252, 0.44792617, 0.09956909])

In [222]:
np.argmax(A)

np.int64(0)

In [223]:
A[np.argmax(A)]

np.float64(0.9840422413641464)

In [224]:
np.argmin(A)

np.int64(4)

In [225]:
A[np.argmin(A)]

np.float64(0.09956908911081108)

In [229]:
np.argsort(A)

array([4, 1, 3, 2, 0])

In [233]:
np.max(A)

np.float64(0.9840422413641464)

In [234]:
np.min(A)

np.float64(0.09956908911081108)

In [235]:
np.mean(A)

np.float64(0.4657801902617743)

In [236]:
np.median(A)

np.float64(0.4479261718707299)

In [237]:
np.std(A)

np.float64(0.30010186623294854)

Indeksowanie i wycinanie tablic

In [238]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [239]:
A[2]

np.int64(2)

In [240]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [241]:
A[:2]

array([0, 1])

In [242]:
A[[0, 2, 3]]

array([0, 2, 3])

In [243]:
A[-1]

np.int64(19)

In [244]:
A[10:15]

array([10, 11, 12, 13, 14])

In [246]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [247]:
A[0]

array([0, 1, 2, 3, 4])

In [248]:
A[1]

array([5, 6, 7, 8, 9])

In [249]:
A[:, 0]

array([ 0,  5, 10, 15])

In [250]:
A[:, -1]

array([ 4,  9, 14, 19])

In [252]:
A[1, 1]

np.int64(6)

In [253]:
A[1, 3]

np.int64(8)

In [255]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [258]:
A[1, 2] = 14

In [259]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [260]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [262]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [264]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [265]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [266]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [267]:
A.shape

(4, 5)

In [268]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [269]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [270]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [275]:
A = np.arange(-10, 10, 1/2)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [276]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [277]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [281]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [282]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [283]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [284]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])